version: '3.9'

services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: lumen.test/php
    container_name: lumen-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on:
      - webserver
      - db

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: "${APP_URL:-lumen-webserver}"
    restart: unless-stopped
    tty: true
    ports:
      - "${APP_HTTP_PORT:-80}:80"
      - "${APP_HTTPS_PORT:-443}:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  # MySQL Service
  db:
    image: mysql:8.0.27
    container_name: "${DB_HOST:-db}"
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_DATABASE: "${DB_DATABASE:-lumen}"
      MYSQL_USER: "${DB_USERNAME:-root}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql-files/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
